#!/system/bin/sh
# ATRILD start script

while true
do
for apk in /system/app/fi.dungeon.atrild*.apk /data/app/fi.dungeon.atrild*.apk
do
	if [ -f "$apk" ] ; then
		log -p i -t ATRIL Starting $apk  
 
	  export CLASSPATH="$apk"
	  app_process -Xbootclasspath:$BOOTCLASSPATH:$CLASSPATH com.android.internal.util.WithFramework fi.dungeon.atrild.root.Main
		log -p e -t ATRIL Process stopped, retrying in 600s
	  sleep 600
	fi
done
done
